# Generated by Django 2.2.6 on 2020-02-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200205_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='postuser',
        ),
    ]
